<h3><a name="1" pa-marked="1"></a>1. Payment Services and Eligibility.</h3>

<p><strong>1.1 Payment Services.</strong>&nbsp;PayPal is a payment services provider and acts as such by creating, hosting, maintaining and providing our PayPal Services to you via the Internet. Our services allow you to send payments to anyone with a PayPal Account, and, where available, to receive payments. Our service availability varies by country/region.&nbsp;We offer services in compliance with local laws and regulations.&nbsp;<a href="https://www.paypal.com/et/webapps/mpp/ua/residence-full" pa-marked="1"><strong>Click here</strong></a>&nbsp;to see which services are available in your country/region of residence.</p>

<p>PayPal is not a remittance business or a money transfer service and the Personal Payments feature may not be used to remit funds to third parties.</p>

<p>We do not have any control over, and are not responsible or liable for, the products or services that are paid for with our PayPal Service. We cannot ensure that a buyer or a Seller you are dealing with will actually complete the transaction.</p>

<p>PayPal is not a common carrier or public utility.</p>

<p><strong>1.2 Eligibility.</strong>&nbsp;To be eligible to use the PayPal Services, you must be at least 18 years old or higher based on the age of majority in your jurisdiction, and a resident of one of the countries listed on the&nbsp;<a href="https://www.paypal.com/et/webapps/mpp/country-worldwide" pa-marked="1"><strong>PayPal Worldwide</strong></a>&nbsp;page.</p>

<p>You must list your correct country/region&nbsp;of residence in your Account. This Agreement applies only to Users who are residents of one of the countries listed in Section 1.1 above. If you are a resident of another country/region, you may access the agreement that applies to you from our website in your country/region.</p>

<p><strong>1.3 Information.</strong>&nbsp;In order to open and maintain an Account, you must provide us with correct and updated Information.</p>

<ol start="1" style="list-style-type: lower-alpha;"> <li style="margin-left: 24pt;"><strong>Your contact information</strong>. It is your responsibility to keep your primary email address up to date so that PayPal can communicate with you electronically. You understand and agree that if PayPal sends you an electronic Communication but you do not receive it because your primary email address on file is incorrect, out of date, blocked by your service provider, or you are otherwise unable to receive electronic Communications, PayPal will be deemed to have provided the Communication to you effectively. Please note that if you use a spam filter that blocks or re-routes emails from senders not listed in your email address book, you must add PayPal to your email address book so that you will be able to view the Communications we send to you.<br> <br> You can update your primary email address or street address at any time by logging into the PayPal website. If your email address becomes invalid such that electronic Communications sent to you by PayPal are returned, PayPal may deem your Account to be inactive, and you will not be able to transact any activity using your PayPal Account until we receive a valid, working primary email address from you.</li> <li style="margin-left: 24pt;"><strong>Identity Verification</strong>. You authorize PayPal, directly or through third parties, to make any inquiries we consider necessary to validate your identity. This may include asking you for further information or documentation, requiring you to provide a taxpayer or national identification number, requiring you to take steps to confirm ownership of your email address or financial instruments, ordering a credit report or verifying your Information against third party databases or through other sources.</li> <li style="margin-left: 24pt;"><strong>Credit Report Authorization</strong>. If you open a Business Account, you are providing PayPal with your written instructions and authorization in accordance with any applicable law to obtain your personal and/or business credit report from a credit bureau. You are also authorizing PayPal to obtain your personal and/or business credit report: (a) when you request certain new products, or (b) at any time PayPal reasonably believes there may be an increased level of risk associated with your Business Account.</li> <li style="margin-left: 24pt;"><strong>Updates to Information</strong>. If your credit card number or expiration date changes, we may update it without any action on your part and we may acquire such updated information from a third party including our financial services partner, the card networks, and your bank or card issuer. If you do not want us to update your card information, you may contact your issuer to request this or remove your Payment Method from your PayPal Account. If we update your Payment Method, we will keep any preference setting attached to such Payment Method.</li> </ol>

<p><strong>1.4 Beneficial Owner.</strong></p>

<p>You must be the beneficial owner of the Account, and conduct business only on behalf of yourself.</p>

<p><strong>1.5 Presentation of PayPal</strong></p>

<p>You agree to provide equal treatment to PayPal and/or other payment methods or marks you offer at your points of sale (e.g. websites or mobile applications). This includes at least equal or substantially similar: logo placement, position within any point of sale, and treatment in terms of payment flow, terms, conditions, restrictions, or fees, in each case as compared to other marks and payment methods at your points of sale.</p>

<p>In representations to your customers or in public communications, you agree not to mischaracterize PayPal as a payment method or exhibit a preference for other payment methods over PayPal. Within all of your points of sale, you agree not to try to dissuade or inhibit your customers from using PayPal or encourage the customer to use an alternate payment method. If you enable your customers to pay you with PayPal, whenever you display or exhibit the payment methods that you accept (either within any point of sale or in your marketing materials, advertising and other customer communications) you agree to display the PayPal payment marks at least as prominently, and in at least as positive a manner, as you do for all other payment methods.</p>
